// ---> TRIVIA REDUCER ACTION <--- 

export const UPDATE_SCORE = "UPDATE_SCORE"
export const SELECT_CHOICE = "SELECT_CHOICE"
export const RESET_CHOICE = "RESET_CHOICE"
export const RESET_SCORE = "RESET_SCORE"
export const BEGIN_TRIVIA = "BEGIN_TRIVIA"
export const ADD_TO_USED_QUESTIONS = "ADD_TO_USED_QUESTIONS"
export const INCREMENT_TOTAL = "INCREMENT_TOTAL"
export const QUESTION_INDEXES = "QUESTION_INDEXES"
